# Generated by Django 4.2.6 on 2024-06-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name', 'last_name', 'middle_name', 'email', 'student_id', 'role', 'password', 'is_superuser', 'is_staff', 'is_active', 'date_joined', 'last_login']},
        ),
    ]
