# Generated by Django 4.2.6 on 2025-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuserrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserRequest',
        ),
    ]
