# Generated by Django 4.2.6 on 2024-08-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='data',
            new_name='date',
        ),
    ]
