# Generated by Django 4.2.6 on 2025-01-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_data_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
