# Generated by Django 4.2.6 on 2025-01-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_capacity_room_code_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='institution',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
