# Generated by Django 4.2.6 on 2024-06-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_intstitution_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
